spring.application.name=transacao-simplificada
# Configuracoes de conexao
spring.datasource.url=jdbc:postgresql://localhost:5432/transacoes
spring.datasource.username=projects_lluis
spring.datasource.password=F1rJ@n

# Dialeto e driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
